DROP TABLE IF EXISTS CURRENCIES;
CREATE TABLE CURRENCIES (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	cur_date DATE NOT NULL UNIQUE,
	usd_rate REAL NOT NULL,
	eur_rate REAL NOT NULL
);

DROP TABLE IF EXISTS REGION;
CREATE TABLE REGION (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	region_name TEXT NOT NULL
);


DROP TABLE IF EXISTS REAL_ESTATE;
CREATE TABLE REAL_ESTATE (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	square INTEGER NOT NULL,
	is_agent INTEGER,
	region_id INTEGER,
	price INTEGER NOT NULL,
	price_per_square REAL NOT NULL,
	room_num INTEGER NOT NULL,
	address TEXT NOT NULL,
	link TEXT NOT NULL UNIQUE,
	ddate DATE NOT NULL DEFAULT CURRENT_DATE,
	FOREIGN KEY(region_id) REFERENCES REGION(id)
);

DROP TABLE IF EXISTS SCRAPE_RUNS;
CREATE TABLE SCRAPE_RUNS (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	finished_at TEXT NOT NULL,
	listings_processed INTEGER NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS LISTING_PRICE_HISTORY;
CREATE TABLE LISTING_PRICE_HISTORY (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	listing_id INTEGER NOT NULL,
	price INTEGER NOT NULL,
	price_per_square REAL NOT NULL,
	scraped_at TEXT NOT NULL,
	FOREIGN KEY(listing_id) REFERENCES REAL_ESTATE(id)
);
CREATE INDEX IF NOT EXISTS idx_listing_price_history_listing_time
	ON LISTING_PRICE_HISTORY(listing_id, scraped_at);

-- Houses for sale (e.g. Dilijan category 1386). Square is often missing on list cards.
DROP TABLE IF EXISTS HOUSE_PRICE_HISTORY;
DROP TABLE IF EXISTS HOUSES;
CREATE TABLE HOUSES (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	square INTEGER,
	is_agent INTEGER,
	region_id INTEGER,
	price INTEGER NOT NULL,
	price_per_square REAL,
	room_num INTEGER NOT NULL,
	address TEXT NOT NULL,
	link TEXT NOT NULL UNIQUE,
	ddate DATE NOT NULL DEFAULT CURRENT_DATE,
	FOREIGN KEY(region_id) REFERENCES REGION(id)
);

CREATE TABLE HOUSE_PRICE_HISTORY (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	listing_id INTEGER NOT NULL,
	price INTEGER NOT NULL,
	price_per_square REAL,
	scraped_at TEXT NOT NULL,
	FOREIGN KEY(listing_id) REFERENCES HOUSES(id)
);
CREATE INDEX IF NOT EXISTS idx_house_price_history_listing_time
	ON HOUSE_PRICE_HISTORY(listing_id, scraped_at);

-- Dilijan long-term rent (apartments category 56 + houses category 1377)
DROP TABLE IF EXISTS DILIJAN_RENT_PRICE_HISTORY;
DROP TABLE IF EXISTS DILIJAN_RENT;
CREATE TABLE DILIJAN_RENT (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	property_type TEXT NOT NULL,
	square INTEGER,
	is_agent INTEGER,
	region_id INTEGER,
	price INTEGER NOT NULL,
	price_per_square REAL,
	room_num INTEGER NOT NULL,
	address TEXT NOT NULL,
	link TEXT NOT NULL UNIQUE,
	ddate DATE NOT NULL DEFAULT CURRENT_DATE,
	FOREIGN KEY(region_id) REFERENCES REGION(id)
);
CREATE TABLE DILIJAN_RENT_PRICE_HISTORY (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	listing_id INTEGER NOT NULL,
	price INTEGER NOT NULL,
	price_per_square REAL,
	scraped_at TEXT NOT NULL,
	FOREIGN KEY(listing_id) REFERENCES DILIJAN_RENT(id)
);
CREATE INDEX IF NOT EXISTS idx_dilijan_rent_type
	ON DILIJAN_RENT(property_type);
CREATE INDEX IF NOT EXISTS idx_dilijan_rent_history_listing_time
	ON DILIJAN_RENT_PRICE_HISTORY(listing_id, scraped_at);
