DROP TABLE IF EXISTS CURRENCIES;
CREATE TABLE CURRENCIES (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	cur_date DATE NOT NULL UNIQUE,
	usd_rate REAL NOT NULL,
	eur_rate REAL NOT NULL
);

DROP TABLE IF EXISTS REGION;
CREATE TABLE REGION (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	region_name TEXT NOT NULL
);


DROP TABLE IF EXISTS REAL_ESTATE;
CREATE TABLE REAL_ESTATE (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	square INTEGER NOT NULL,
	is_agent INTEGER,
	region_id INTEGER,
	price INTEGER NOT NULL,
	price_per_square REAL NOT NULL,
	room_num INTEGER NOT NULL,
	address TEXT NOT NULL,
	link TEXT NOT NULL UNIQUE,
	ddate DATE NOT NULL DEFAULT CURRENT_DATE,
	FOREIGN KEY(region_id) REFERENCES REGION(id)
);

DROP TABLE IF EXISTS SCRAPE_RUNS;
CREATE TABLE SCRAPE_RUNS (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	finished_at TEXT NOT NULL,
	listings_processed INTEGER NOT NULL DEFAULT 0
);
